services:
  db:
    image: mysql:8
    container_name: mysql_commandas_api
    environment:
      MYSQL_ROOT_PASSWORD: abcBolinhas12345
      MYSQL_DATABASE: comandas_db
      MYSQL_USER: coelho
      MYSQL_PASSWORD: abcBolinhas12345
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  comandas_api:
    image: rafaelblomer/comanda-api:latest
    container_name: comandas_api
    depends_on:
      - db
    environment:
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: coelho
      MYSQL_DB_PASSWORD: abcBolinhas12345
    ports:
      - "4443:4443"
    restart: always

volumes:
  db_data:
    driver: local
