#Rafael Ceccatto Blomer
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDIyNjU5NTV9.s2yH75W4v8lLIvGrKE_5cVqMOzMT9aHR5yIqS3LytzQ

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar todos
curl -X 'GET' 'http://localhost:8000/funcionario/' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer {{token}}'

### ao logar, gera um token que deve ser usado para acessar as rotas da API
curl -X 'POST' 'http://127.0.0.1:8000/token' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'username=abc&password=bolinhas'

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "Rafael Ceccatto Blomer",
    "matricula" : "rafael12353",
    "cpf" : "1",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "ee29eb4a8725678278ac4320e7"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "Rafael teste",
    "matricula" : "teste",
    "cpf" : "1",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "dc7378a6b6316017b81c51d720e7"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}