#Rafael Ceccatto Blomer
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDIyNjU5NTV9.s2yH75W4v8lLIvGrKE_5cVqMOzMT9aHR5yIqS3LytzQ

### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "Rafael Ceccatto Blomer",
    "cpf" : "3",
    "telefone" : "tel2383738"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "Teste",
    "cpf" : "1",
    "telefone" : "tel2383738"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{token}}