#Rafael Ceccatto Blomer
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDIyNjU5NTV9.s2yH75W4v8lLIvGrKE_5cVqMOzMT9aHR5yIqS3LytzQ

### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar um
GET http://localhost:8000/produto/1 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "rafael",
    "descricao" : "produto1",
    "valor_unitario": 1.50,
    "foto" : "b'89PNG\r\n1a\n'"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "teste",
    "descricao" : "produto1000",
    "valor_unitario": 1.50,
    "foto" : "b'89PNG\r\n1a\n'"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1
Authorization: Bearer {{token}}